sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        send_default_pii: true

when@dev:
    sentry:
        register_error_listener: true
    services:
        Sentry\Monolog\Handler:
            arguments:
                - '@Sentry\State\HubInterface'
                - !php/const Monolog\Logger::DEBUG
                - true # bubble
                - true # fillExtraContext

when@prod:
    sentry:
        register_error_listener: true
    services:
        Sentry\Monolog\Handler:
            arguments:
                - '@Sentry\State\HubInterface'
                - !php/const Monolog\Logger::ERROR
                - true # bubble
                - true # fillExtraContext
